swagger: "2.0"

info:
  version: 1.0.0
  title: Clinic System
  description: This is our Clinic System API if you have any information just refer to a.mahdy@rkanjel
schemes:
  - https
host: simple.api
basePath: /openapi101

paths: {}